module.exports = [
  {
    emp_id: "MH2007TCR653490",
    emp_name: "Kunal",
    district: "Satara",
    block: "Jaoli",
    school_name: "M G D S School",
    year_of_joining: "2005",
    work_here_since: "2007",
    gender: "Female",
    caste: "SC",
    DOB: "01/01/01",
    post: "Head Teacher",
    subject: "Maths",
    class: "II to X",
    disability: "Yes",
    nominee: "Jatin Sharma",
    nominee_relation: "Son",
  },
  {
    emp_id: "MH2011ADM653420",
    emp_name: "Jatin",
    district: "Satara",
    block: "Karad",
    school_name: "SSGB School",
    year_of_joining: "2005",
    work_here_since: "2011",
    gender: "Male",
    caste: "OBC",
    DOB: "21/11/05",
    post: "Teacher",
    subject: "Biology",
    class: "V to XII",
    disability: "No",
    nominee: "Kartik",
    nominee_relation: "Father",
  },
  {
    emp_id: "MH2007BSA653214",
    emp_name: "Kartik",
    district: "Mumbai",
    block: "",
    school_name: "M G D S School",
    year_of_joining: "2005",
    work_here_since: "2007",
    gender: "Female",
    caste: "SC",
    DOB: "01/01/01",
    post: "Head Teacher",
    subject: "Maths",
    class: "II to X",
    disability: "Yes",
    nominee: "Jatin Sharma",
    nominee_relation: "Son",
  },
];