module.exports = [
  {
    name: "Deadpool",
    leaveType: "leave",
    dayType: "full",
    from: "08/23/2002",
    to: "01/01/2001",
    department: "science",
    supervisor: "Dead",
    reason: "medical",
    postingDate: "12-03-2022",
    status: "pending",
  },
  {
    name: "Deadpool",
    leaveType: "leave",
    dayType: "full",
    from: "08/23/2002",
    to: "01/01/2001",
    department: "science",
    supervisor: "Dead",
    reason: "medical",
    postingDate: "12-03-2022",
    status: "pending",
  },
  {
    name: "Deadpool",
    leaveType: "leave",
    dayType: "full",
    from: "08/23/2002",
    to: "01/01/2001",
    department: "science",
    supervisor: "Dead",
    reason: "medical",
    postingDate: "12-03-2022",
    status: "pending",
  },
  {
    name: "Deadpool",
    leaveType: "leave",
    dayType: "full",
    from: "08/23/2002",
    to: "01/01/2001",
    department: "science",
    supervisor: "Dead",
    reason: "medical",
    postingDate: "12-03-2022",
    status: "pending",
  },
];
