module.exports = [
  {
    Fullname: "Kunal Kumar",
    city: "New Delhi",
    phone: "8345231451",
    email: "kunalkumar@gmail.com",
    age: "41",
    subject: "Psychology",
    education: "Phd in management",
    skillOne: "MS Office",
    skillTwo: "Photoshop",
    skillThree: "",
    about: "",
    experience: "25",
  },
  {
    Fullname: "Kunal Kumar",
    city: "New Delhi",
    phone: "8345231451",
    email: "kunalkumar@gmail.com",
    age: "41",
    subject: "Psychology",
    education: "Phd in management",
    skillOne: "MS Office",
    skillTwo: "Photoshop",
    skillThree: "",
    about: "",
    experience: "25",
  },
  {
    Fullname: "Kunal Kumar",
    city: "New Delhi",
    phone: "8345231451",
    email: "kunalkumar@gmail.com",
    age: "41",
    subject: "Psychology",
    education: "Phd in management",
    skillOne: "MS Office",
    skillTwo: "Photoshop",
    skillThree: "",
    about: "",
    experience: "25",
  },
];
