module.exports = [
  {
    school_type: "Elementary",
    state: "Delhi",
    mobileNo: "1234578976",
    dob: "15/11/1999",
    email: "ssbnic@gmail.com",
    presentSchool: "delhi governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "01/01/2001",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "pusa"],
  },
  {
    school_type: "Elementary",
    state: "Delhi",
    mobileNo: "1234578976",
    dob: "15/11/1999",
    email: "ssbnic@gmail.com",
    presentSchool: "delhi governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "01/01/2001",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "pusa"],
  },
  {
    school_type: "Elementary",
    state: "Delhi",
    mobileNo: "1234578976",
    dob: "15/11/1999",
    email: "ssbnic@gmail.com",
    presentSchool: "delhi governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "01/01/2001",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "pusa"],
  },
];
