module.exports = [
  {
    application_no: "2911556b-038a-42f1-9f8c-771df9e5578b",
    school_type: "Elementary",
    name: "Kunal Kumar",
    gender: "Male",
    state: "Delhi",
    mobileNo: "1234578976",
    dob: "15/11/1999",
    email: "ssbnic@gmail.com",
    presentSchool: "delhi governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "01/01/2001",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "Amritsar"],
  },
  {
    application_no: "2911556b-038a-42f1-9f8c-771df9e5578b",
    school_type: "Elementary",
    name: "Simarpreet Singh",
    gender: "Male",
    state: "Delhi",
    mobileNo: "1234578976",
    dob: "15/11/1999",
    email: "ssbnic@gmail.com",
    presentSchool: "Goa governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "01/01/2001",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "pusa"],
  },
  {
    application_no: "2911556b-038a-42f1-9f8c-771df9e5578b",
    school_type: "Elementary",
    name: "Kritika Jain",
    gender: "Female",
    state: "Goa",
    mobileNo: "963852741",
    dob: "10/12/1999",
    email: "kritika@gmail.com",
    presentSchool: "Goa governmental school",
    district: "dwarka",
    subject: "maths",
    currentDesignation: "HOD",
    dateOfJoining: "12/12/2008",
    maritalStatus: "married",
    reason: "divorcee",
    preferences: ["dwarka", "Ujjain"],
  },
];
